apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260615-200226-2ayt0sa00tuv-service
spec:
  selector:
    app: enterprise-system-20260615-200226-2ayt0sa00tuv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
